version: '3.8'
services:
  cu:
    build:
      context: ./servers/cu
    environment:
      - NODE_CONFIG_ENV="development"
      - NODE_HEAPDUMP_OPTIONS="nosignal"
      - DEBUG=*
      - WALLET="wallet.json"
    ports: [ 3001:3001 ]
    # Add any additional configuration for the cu service if needed
  mu:
    build:
      context: ./servers/mu
    environment:
      - PORT=3002
      - CU_URL="http://localhost:3001"
      - GATEWAY_URL="https://arweave.net"
      - NODE_CONFIG_ENV="development"
      - DEBUG=*
      - PATH_TO_WALLET="wallet.json"
    ports: [ 3002:3002 ]
    depends_on:
      - cu
    # Add any additional configuration for the mu service if needed
  su:
    build:
      context: ./servers/su
    environment:
      - SU_WALLET_PATH=./.wallet.json
      - DATABASE_URL=postgresql://user:password@localhost/su
      - GATEWAY_URL=https://arweave.net/
      - UPLOAD_NODE_URL=https://up.arweave.net
      - MODE=su
      - SCHEDULER_LIST_PATH=""
    ports: [ 3003:3003 ]
    # Add any additional configuration for the su service if needed
